'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {evaluate}=require('../core/dispatch'),f=require('./jobs-fixtures'),s=require('../normalization/schedules');
test('AWS DST spring gap skipped and fallback fires once',()=>{
  const job={dialect:'aws-scheduler',expression:'cron(30 2 * * ? *)',timezone:'America/New_York'};
  assert.deepEqual(s.occurrences(job,Date.parse('2026-03-08T00:00:00Z'),Date.parse('2026-03-09T00:00:00Z'),10),[]);
  job.expression='cron(30 1 * * ? *)';assert.equal(s.occurrences(job,Date.parse('2026-11-01T00:00:00Z'),Date.parse('2026-11-02T00:00:00Z'),10).length,1);
});
test('AWS weekday conversion and fixed 24-hour rate',()=>{
  const job={dialect:'aws-scheduler',expression:'cron(0 1 ? * 2 *)',timezone:'UTC'};
  assert.equal(s.occurrences(job,Date.parse('2026-10-05T00:00:00Z'),Date.parse('2026-10-06T00:00:00Z'),10).length,1);
  const rate={dialect:'aws-scheduler',expression:'rate(1 day)',timezone:'America/New_York',start:'2026-03-07T12:00:00Z'};
  const dates=s.occurrences(rate,Date.parse(rate.start),Date.parse('2026-03-10T12:00:00Z'),10);assert.equal(dates[1]-dates[0],86400000);
});
test('disabled, independent pools, serialized and sufficient capacity suppress',()=>{for(const mutate of [i=>{i.sources[0].data.jobs[1].enabled=false;},i=>{i.sources[0].data.jobs[1].pool_id='other';},i=>{i.sources[0].data.jobs[1].serialized=true;},i=>{i.sources[0].data.jobs.forEach(j=>{j.pool_capacity=2;});}]){const i=f.schedule();mutate(i);assert.equal(evaluate(i).findings.length,0);}});
test('flexible window, unsupported timezone, yearly AWS constraints and occurrence limit unavailable',()=>{for(const mutate of [i=>{i.sources[0].data.jobs[1].flexible_window_seconds=900;},i=>{i.sources[0].data.jobs[1].timezone='Unknown/Zone';},i=>{i.sources[0].data.jobs[1].dialect='aws-scheduler';i.sources[0].data.jobs[1].expression='cron(0 1 * * ? 2026)';},i=>{i.context.max_occurrences=1;i.sources[0].data.jobs[0].expression='* * * * *';}]){const i=f.schedule();mutate(i);assert.equal(evaluate(i).status,'unavailable');}});
test('idle workers: missing samples, unit values, shared duties and backlog',()=>{let i=f.workers();i.sources[0].data.samples.pop();assert.equal(evaluate(i).status,'unavailable');for(const k of ['shared_workload','leader_or_heartbeat_duties']){i=f.workers();i.sources[0].data.policy[k]=true;assert.equal(evaluate(i).findings.length,0);}i=f.workers();i.sources[0].data.samples[3].queue_depth=10;assert.equal(evaluate(i).findings.length,0);i=f.workers();i.sources[0].data.samples.forEach(s=>{s.workers=0;s.busy_worker_seconds=0;});assert.equal(evaluate(i).findings.length,0);});
test('unchanged output alone, failure/retry, external dependency and hidden input are not wasted rebuild proof',()=>{for(const mutate of [i=>{i.sources[0].data.policy.all_inputs_versioned=false;},i=>{i.sources[0].data.policy.external_dependencies=true;},i=>{i.sources[0].data.policy.reconciliation=true;},i=>{i.sources[0].data.runs[1].outcome='failed';},i=>{i.sources[0].data.runs[1].attempt=2;},i=>{delete i.sources[0].data.runs[1].input_version;}]){const i=f.runs();mutate(i);assert.equal(evaluate(i).findings.length,0);}});
test('request source-only candidate is labelled, runtime cannot omit telemetry',()=>{const i=f.request('JOB-01','candidate');assert.match(evaluate(i).findings[0].summary,/runtime cost unverified/);i.context.mode='runtime';assert.equal(evaluate(i).status,'unavailable');});
test('request fingerprint survives source line movement with renewed source digest',()=>{const i=f.request('JOB-01','candidate'),before=evaluate(i);i.sources[0].content='// heading\n'+i.sources[0].content;i.sources[1].data.source_sha256=crypto.createHash('sha256').update(i.sources[0].content).digest('hex');const after=evaluate(i);assert.equal(after.findings[0].fingerprint,before.findings[0].fingerprint);assert.equal(after.findings[0].evidence[0].line_start,3);});
test('request comments, strings and unsupported branching never pretend a call is present',()=>{const i=f.request('JOB-01','candidate');i.sources[0].content='function handler(req, res) {\n  "report.generate(req)";\n  return res.send("accepted");\n}';i.sources[1].data.source_sha256=crypto.createHash('sha256').update(i.sources[0].content).digest('hex');assert.equal(evaluate(i).findings.length,0);i.sources[0].content='function handler(req, res) { if (req) report.generate(req); return res.send("ok"); }';i.sources[1].data.source_sha256=crypto.createHash('sha256').update(i.sources[0].content).digest('hex');assert.equal(evaluate(i).status,'unavailable');});
test('messaging requires complete inventory and human approval remains separate',()=>{const i=f.request('JOB-06');assert.match(evaluate(i).findings[0].summary,/human review/);i.sources[1].data.deployment_inventory_complete=false;assert.equal(evaluate(i).status,'unavailable');});
