'use strict';
// Committed cases for the static ORM checks. kind: positive | negative | exception | missing | malformed | boundary.
// `identities` lists the expected finding identities (semantic anchors, no line numbers); `status` the coverage status.
const cases = {
  'DB-39': [
    {id: 1, kind: 'positive', name: 'Django queryset slice from a request-derived page', path: 'app/views.py',
      content: 'def article_page(page):\n    return Article.objects.filter(live=True)[page * 10:page * 10 + 10]\n', identities: ['article_page:django.slice']},
    {id: 2, kind: 'positive', name: 'SQLAlchemy .offset() with a variable', path: 'app/repo.py',
      content: 'class Repo:\n    def page(self, n):\n        return session.query(User).order_by(User.id).offset(n * 20).limit(20).all()\n', identities: ['Repo.page:sqlalchemy.offset']},
    {id: 3, kind: 'positive', name: 'Prisma findMany skip with a variable', path: 'src/users.ts',
      content: 'export async function listUsers(page: number) {\n  return prisma.user.findMany({ skip: page * 10, take: 10 });\n}\n', identities: ['listUsers:option.skip']},
    {id: 4, kind: 'positive', name: 'Sequelize findAll offset and Knex .offset()', path: 'src/repo.js',
      content: 'async function a(n) { return Post.findAll({ offset: n, limit: 10 }); }\nfunction b(n) { return knex("posts").offset(n).limit(10); }\n', identities: ['a:option.offset', 'b:builder.offset']},
    {id: 5, kind: 'positive', name: 'raw SQL OFFSET placeholder (python) and LIMIT a,b (ts)', path: 'src/raw.py',
      content: 'def f(cur, off):\n    cur.execute("SELECT id FROM t ORDER BY id LIMIT 10 OFFSET %s", (off,))\n', identities: ['f:raw-sql.offset']},
    {id: 6, kind: 'positive', name: 'two raw queries in one function get stable ordinals', path: 'src/two.ts',
      content: 'async function f(db, o) {\n  await db.query("SELECT a FROM t OFFSET $1", [o]);\n  await db.query("SELECT b FROM t OFFSET $1", [o]);\n}\n', identities: ['f:raw-sql.offset', 'f:raw-sql.offset#2']},
    {id: 7, kind: 'negative', name: 'seek pagination has no offset', path: 'src/seek.ts',
      content: 'export const next = (last: number) => prisma.user.findMany({ where: { id: { gt: last } }, orderBy: { id: "asc" }, take: 10 });\n', identities: []},
    {id: 8, kind: 'negative', name: 'plain list slice is not a queryset', path: 'app/util.py',
      content: 'def head(items, n):\n    return items[n:n + 10]\n', identities: []},
    {id: 9, kind: 'negative', name: 'SQL without OFFSET', path: 'app/q.py',
      content: 'Q = "SELECT id FROM t ORDER BY id LIMIT 10"\n', identities: []},
    {id: 10, kind: 'exception', name: 'skip: 0 and a small literal offset are exempt', path: 'src/first.ts',
      content: 'export const a = () => prisma.user.findMany({ skip: 0, take: 5 });\nexport const b = () => knex("t").offset(5);\n', identities: []},
    {id: 11, kind: 'boundary', name: 'literal offset exactly at the minimum is flagged', path: 'src/edge.js',
      content: 'function f() { return knex("t").offset(100); }\n', identities: ['f:builder.offset']},
    {id: 12, kind: 'boundary', name: 'literal offset one below the minimum is exempt', path: 'src/edge2.js',
      content: 'function f() { return knex("t").offset(99); }\n', identities: []},
    {id: 13, kind: 'missing', name: 'no source for the requested scope is unavailable, never clean', path: 'src/none.ts', content: null, identities: [], status: 'unavailable'},
    {id: 14, kind: 'malformed', name: 'syntax error file is not evaluated', path: 'app/bad.py', content: 'def f(:\n    pass\n', identities: [], status: 'unavailable'},
    {id: 15, kind: 'malformed', name: 'unsupported language is not evaluated', path: 'app/Thing.php', content: '<?php echo 1;', identities: [], status: 'unavailable'},
    {id: 16, kind: 'positive', name: 'Django queryset held in a variable then sliced', path: 'app/paged.py',
      content: 'def page(request, n):\n    qs = Item.objects.filter(live=True).order_by("id")\n    return qs[n * 25:(n + 1) * 25]\n', identities: ['page:django.slice']},
    {id: 17, kind: 'negative', name: 'slicing a materialised list(qs) is not a queryset offset', path: 'app/listed.py',
      content: 'def page(n):\n    rows = list(Item.objects.all())\n    return rows[n:n + 10]\n', identities: []},
    {id: 18, kind: 'boundary', name: 'KNOWN LIMIT: skip inside a wrapper-method options object (listAndCount) is not recognised', path: 'src/svc.ts',
      content: 'export async function list(svc, page: number) {\n  return svc.listAndCount({}, { skip: page * 20, take: 20 });\n}\n', identities: []},
    {id: 19, kind: 'negative', name: 'bare {offset, limit} response metadata object is not a query', path: 'src/resp.ts',
      content: 'export function respond(items, offset: number) {\n  return res.json({ items, offset, limit: 10 });\n}\n', identities: []},
    {id: 20, kind: 'negative', name: 'offset on a non-find callee is ignored', path: 'src/meta.ts',
      content: 'export const x = (o: number) => build({ offset: o });\n', identities: []},
  ],
  'DB-13': [
    {id: 1, kind: 'positive', name: 'Django per-row save() over a queryset', path: 'app/sync.py',
      content: 'def sync(items):\n    for item in items:\n        item.price = item.price * 2\n        item.save()\n', identities: ['sync:django.save-in-for']},
    {id: 2, kind: 'positive', name: 'Django objects.create per element and filter().update() per element', path: 'app/load.py',
      content: 'def load(rows):\n    for r in rows:\n        Product.objects.create(sku=r["sku"])\n    for r in rows:\n        Product.objects.filter(sku=r["sku"]).update(seen=True)\n',
      identities: ['load:django.create-in-for', 'load:django.update-in-for']},
    {id: 3, kind: 'positive', name: 'SQLAlchemy session.add per row and raw INSERT per row', path: 'app/orm.py',
      content: 'def f(session, cur, rows):\n    for r in rows:\n        session.add(Row(id=r))\n    for r in rows:\n        cur.execute("INSERT INTO t (id) VALUES (%s)", (r,))\n',
      identities: ['f:session.add-in-for', 'f:raw-sql.execute-in-for']},
    {id: 4, kind: 'positive', name: 'comprehension that creates one row per element', path: 'app/comp.py',
      content: 'def f(rows):\n    return [Product.objects.create(sku=r) for r in rows]\n', identities: ['f:django.create-in-comprehension']},
    {id: 5, kind: 'positive', name: 'Prisma update inside for-of and Promise.all(map)', path: 'src/jobs.ts',
      content: 'export async function a(users: User[]) {\n  for (const u of users) {\n    await prisma.user.update({ where: { id: u.id }, data: { seen: true } });\n  }\n}\nexport async function b(users: User[]) {\n  await Promise.all(users.map(async (u) => prisma.user.delete({ where: { id: u.id } })));\n}\n',
      identities: ['a:orm.update-in-for-of', 'b:orm.delete-in-map']},
    {id: 6, kind: 'positive', name: 'Knex insert and raw UPDATE per row in forEach', path: 'src/rows.js',
      content: 'async function f(rows) {\n  for (let i = 0; i < rows.length; i++) { await knex("t").insert(rows[i]); }\n  rows.forEach((r) => db.query("UPDATE t SET a = 1 WHERE id = " + r.id));\n}\n',
      identities: ['f:orm.insert-in-for', 'f:raw-sql.query-in-forEach']},
    {id: 7, kind: 'negative', name: 'bulk APIs are the fix, not the problem', path: 'app/bulk.py',
      content: 'def f(rows, session, cur):\n    Product.objects.bulk_create([Product(sku=r) for r in rows])\n    session.add_all(rows)\n    cur.executemany("INSERT INTO t VALUES (%s)", rows)\n', identities: []},
    {id: 8, kind: 'negative', name: 'JS createMany / updateMany outside a loop', path: 'src/bulk.ts',
      content: 'export async function f(users: User[]) {\n  await prisma.user.createMany({ data: users });\n  await prisma.user.updateMany({ data: { seen: true } });\n}\n', identities: []},
    {id: 9, kind: 'negative', name: 'write that does not depend on the loop variable', path: 'app/const.py',
      content: 'def f(items):\n    for item in items:\n        print(item)\n    Audit.objects.create(kind="done")\n    for _ in items:\n        Audit.objects.create(kind="tick")\n', identities: []},
    {id: 10, kind: 'negative', name: 'a .save() with a positional argument is not a model save (PIL image)', path: 'app/img.py',
      content: 'def f(images):\n    for im in images:\n        im.save("out.png")\n', identities: []},
    {id: 11, kind: 'negative', name: 'a set .add() and a list .append() in a loop are not DB writes', path: 'app/sets.py',
      content: 'def f(items):\n    seen = set()\n    for i in items:\n        seen.add(i)\n    return seen\n', identities: []},
    {id: 12, kind: 'exception', name: 'loop over a short literal list is exempt', path: 'app/few.py',
      content: 'def f():\n    for name in ["a", "b", "c"]:\n        Role.objects.create(name=name)\n    for i in range(3):\n        Role.objects.create(name=str(i))\n', identities: []},
    {id: 13, kind: 'boundary', name: 'literal list above the threshold is flagged, at the threshold exempt', path: 'app/edge.py',
      content: 'def over():\n    for n in ["a", "b", "c", "d", "e", "f"]:\n        Role.objects.create(name=n)\ndef at():\n    for n in ["a", "b", "c", "d", "e"]:\n        Role.objects.create(name=n)\n', identities: ['over:django.create-in-for']},
    {id: 14, kind: 'positive', name: 'name derived from the loop variable inside the body counts', path: 'app/derived.py',
      content: 'def f(rows):\n    for r in rows:\n        row = Row(sku=r)\n        session.add(row)\n', identities: ['f:session.add-in-for']},
    {id: 17, kind: 'negative', name: 'TypeORM/MikroORM manager.create() is an in-memory entity, not a write', path: 'src/entities.ts',
      content: 'export function build(em, rows) {\n  return rows.map((r) => em.create(Entity, r));\n}\n', identities: []},
    {id: 18, kind: 'positive', name: 'one-off seed/management script keeps the finding at low confidence', path: 'shop/management/commands/seed.py', confidence: 'low',
      content: 'def seed(rows):\n    for r in rows:\n        Product.objects.create(sku=r)\n', identities: ['seed:django.create-in-for']},
    {id: 19, kind: 'positive', name: 'update_or_create per row is reported at low confidence', path: 'app/upsert.py', confidence: 'low',
      content: 'def f(rows):\n    for r in rows:\n        Product.objects.update_or_create(sku=r)\n', identities: ['f:django.update_or_create-in-for']},
    {id: 20, kind: 'exception', name: 'loop stepping by batchSize already writes one batch per iteration', path: 'src/batches.ts',
      content: 'export async function f(rows: Row[], batchSize: number) {\n  for (let i = 0; i < rows.length; i += batchSize) {\n    await knex("t").insert(rows.slice(i, i + batchSize));\n  }\n}\n', identities: []},
    {id: 21, kind: 'exception', name: 'range(0, n, step) batching loop is exempt', path: 'app/batches.py',
      content: 'def f(rows, session):\n    for i in range(0, len(rows), 500):\n        session.add(Batch(rows[i:i + 500]))\n', identities: []},
    {id: 15, kind: 'missing', name: 'no source for the requested scope is unavailable', path: 'app/none.py', content: null, identities: [], status: 'unavailable'},
    {id: 16, kind: 'malformed', name: 'syntax error file is not evaluated', path: 'src/bad.ts', content: 'export const = ;\n', identities: [], status: 'unavailable'},
  ],
  'DB-23': [
    {id: 1, kind: 'positive', name: 'Django queryset iterated and list()-ed without a slice', path: 'app/views.py',
      content: 'def a():\n    for p in Product.objects.filter(live=True):\n        print(p)\ndef b():\n    return list(Product.objects.all().order_by("name"))\n',
      identities: ['a:django.queryset', 'b:django.queryset']},
    {id: 16, kind: 'positive', name: 'a read with a filter is low confidence (scoped to a parent), a whole-table read is medium', path: 'src/rank.ts', confidence: 'low',
      content: 'export const a = (userId: number) => prisma.membership.findMany({ where: { userId } });\n', identities: ['a:option.findMany']},
    {id: 18, kind: 'negative', name: 'findMany(query) with a variable argument has an unknown limiter and is not flagged', path: 'src/ctl.ts',
      content: 'export const a = async (query: object) => await documents.findMany(query);\n', identities: []},
    {id: 19, kind: 'exception', name: 'unique id compared with a quoted literal is exempt', path: 'src/soql.ts',
      content: 'export const a = async (conn) => await conn.query("SELECT Id, Name FROM User WHERE Id = \'005xx\'");\n', identities: []},
    {id: 20, kind: 'positive', name: 'one-off integration-test helper keeps the finding at low confidence', path: 'integration-tests/helpers/db.ts', confidence: 'low',
      content: 'export const a = () => prisma.country.findMany();\n', identities: ['a:option.findMany']},
    {id: 17, kind: 'positive', name: 'a whole-table read without any filter is medium confidence', path: 'src/whole.ts', confidence: 'medium',
      content: 'export const a = () => prisma.country.findMany();\n', identities: ['a:option.findMany']},
    {id: 2, kind: 'positive', name: 'SQLAlchemy .all() without limit, query() and select() styles', path: 'app/repo.py',
      content: 'def a(session):\n    return session.query(User).filter(User.active).all()\ndef b(session):\n    return session.execute(select(User)).scalars().all()\n',
      identities: ['a:sqlalchemy.all', 'b:sqlalchemy.all']},
    {id: 3, kind: 'positive', name: 'Prisma findMany without take, Sequelize findAll without limit', path: 'src/repo.ts',
      content: 'export const a = () => prisma.user.findMany({ where: { active: true } });\nexport const b = () => User.findAll({ where: { active: true } });\nexport const c = () => prisma.post.findMany();\n',
      identities: ['a:option.findMany', 'b:option.findAll', 'c:option.findMany']},
    {id: 4, kind: 'positive', name: 'TypeORM find() and QueryBuilder getMany() without take', path: 'src/orm.ts',
      content: 'export async function a(userRepository) {\n  return userRepository.find({ where: { active: true } });\n}\nexport async function b(dataSource) {\n  return dataSource.createQueryBuilder().select("u").from(User, "u").getMany();\n}\n',
      identities: ['a:option.find', 'b:querybuilder.getMany']},
    {id: 5, kind: 'positive', name: 'raw SELECT without LIMIT in python and node', path: 'src/raw.py',
      content: 'def a(cur):\n    cur.execute("SELECT id, name FROM users WHERE active = true ORDER BY name")\ndef b(cur):\n    cur.execute(f"SELECT * FROM {table}")\n',
      identities: ['a:raw-sql.select', 'b:raw-sql.select']},
    {id: 6, kind: 'positive', name: 'awaited Knex select without limit', path: 'src/knex.ts',
      content: 'export async function f() {\n  return await knex("users").select("id").where({ active: true });\n}\n', identities: ['f:builder.select']},
    {id: 7, kind: 'negative', name: 'limited / sliced / streamed / terminal reads are bounded', path: 'app/bounded.py',
      content: 'def a():\n    for p in Product.objects.filter(live=True)[:50]:\n        print(p)\n    for p in Product.objects.iterator():\n        print(p)\n    x = Product.objects.filter(live=True).count()\n    y = Product.objects.first()\n    return list(Product.objects.all()[:10])\ndef b(session):\n    return session.query(User).limit(20).all()\n', identities: []},
    {id: 8, kind: 'negative', name: 'take / limit present and aggregates are bounded in JS', path: 'src/bounded.ts',
      content: 'export const a = () => prisma.user.findMany({ take: 20 });\nexport const b = () => User.findAll({ limit: 10 });\nexport const c = async () => await knex("users").select("id").limit(10);\nexport const d = async () => await knex("users").count("id");\n', identities: []},
    {id: 9, kind: 'negative', name: 'options with a spread have an unknown limiter and are not flagged', path: 'src/spread.ts',
      content: 'export const a = (opts) => prisma.user.findMany({ ...opts, where: { active: true } });\n', identities: []},
    {id: 10, kind: 'exception', name: 'unique-key lookups and aggregate-only selects are exempt', path: 'src/unique.py',
      content: 'def a(cur, uid):\n    cur.execute("SELECT * FROM users WHERE id = %s", (uid,))\ndef b(cur):\n    cur.execute("SELECT COUNT(*) FROM users")\ndef c(cur):\n    cur.execute("INSERT INTO archive SELECT * FROM users")\n', identities: []},
    {id: 11, kind: 'exception', name: 'Prisma findMany filtered by unique id is exempt', path: 'src/byid.ts',
      content: 'export const a = (id: number) => prisma.user.findMany({ where: { id } });\n', identities: []},
    {id: 12, kind: 'negative', name: 'a lazy queryset that is only stored or returned is not flagged', path: 'app/lazy.py',
      content: 'def a():\n    qs = Product.objects.filter(live=True)\n    return qs\n', identities: []},
    {id: 13, kind: 'negative', name: 'Array.find and a non-DB receiver are not repository reads', path: 'src/array.ts',
      content: 'export const a = (items: X[]) => items.find({ id: 1 } as any);\nexport const b = (items: X[]) => items.find((i) => i.id === 1);\n', identities: []},
    {id: 14, kind: 'missing', name: 'no source for the requested scope is unavailable', path: 'app/none.py', content: null, identities: [], status: 'unavailable'},
    {id: 15, kind: 'malformed', name: 'syntax error file is not evaluated', path: 'app/bad.py', content: 'for x in :\n', identities: [], status: 'unavailable'},
  ],
  'DB-14': [
    {id: 1, kind: 'positive', name: 'raw SELECT * in python and node drivers', path: 'src/raw.py',
      content: 'def a(cur):\n    cur.execute("SELECT * FROM users WHERE active = true")\ndef b(cur, t):\n    cur.execute(f"SELECT * FROM {t}")\n',
      identities: ['a:raw-sql.select-star', 'b:raw-sql.select-star']},
    {id: 2, kind: 'positive', name: 'qualified star, DISTINCT star and star with extra columns', path: 'src/shapes.ts',
      content: 'export async function a(db) {\n  await db.query("SELECT u.* FROM users u JOIN teams t ON t.id = u.team_id");\n  await db.query("SELECT DISTINCT * FROM orders");\n  await db.query("SELECT *, now() AS ts FROM events");\n}\n',
      identities: ['a:raw-sql.select-star', 'a:raw-sql.select-star#2', 'a:raw-sql.select-star#3']},
    {id: 3, kind: 'positive', name: 'explicit Knex select(\'*\')', path: 'src/knex.js',
      content: 'async function f() { return knex("users").select("*").where({ active: true }); }\n', identities: ['f:builder.select-star']},
    {id: 4, kind: 'negative', name: 'COUNT(*), EXISTS (SELECT *), INSERT ... SELECT * and explicit columns are not flagged', path: 'src/ok.py',
      content: 'def a(cur):\n    cur.execute("SELECT COUNT(*) FROM users")\n    cur.execute("SELECT id FROM t WHERE EXISTS (SELECT * FROM u WHERE u.t_id = t.id)")\n    cur.execute("INSERT INTO archive SELECT * FROM users")\n    cur.execute("SELECT id, name FROM users")\n',
      identities: []},
    {id: 5, kind: 'negative', name: 'a star over a derived table with explicit inner columns is a wrapper', path: 'src/wrap.py',
      content: 'def a(cur):\n    cur.execute("SELECT * FROM (SELECT id, name FROM users) AS x")\n', identities: []},
    {id: 6, kind: 'negative', name: 'SQL that is not passed to an execute/query call is not examined', path: 'src/const.py',
      content: 'QUERY = "SELECT * FROM users"\n', identities: []},
    {id: 7, kind: 'exception', name: 'a table the project allows (small config table) is exempt', path: 'src/cfg.py', ctx: {select_star_allowed_tables: ['settings']},
      content: 'def a(cur):\n    cur.execute("SELECT * FROM settings")\n', identities: []},
    {id: 8, kind: 'positive', name: 'one-off script keeps the finding at low confidence', path: 'scripts/dump.py', confidence: 'low',
      content: 'def a(cur):\n    cur.execute("SELECT * FROM users")\n', identities: ['a:raw-sql.select-star']},
    {id: 9, kind: 'missing', name: 'no source for the requested scope is unavailable', path: 'src/none.py', content: null, identities: [], status: 'unavailable'},
    {id: 10, kind: 'malformed', name: 'syntax error file is not evaluated', path: 'src/bad.js', content: 'function ( {\n', identities: [], status: 'unavailable'},
  ],
  'DB-41': [
    {id: 1, kind: 'positive', name: 'sync psycopg2 connection used inside async def', path: 'app/api.py',
      content: 'import psycopg2\n\nasync def handler(request):\n    conn = psycopg2.connect("dbname=x")\n    cur = conn.cursor()\n    cur.execute("SELECT 1")\n    return cur.fetchall()\n',
      identities: ['handler:sync-driver.connect', 'handler:sync-driver.cursor', 'handler:sync-driver.execute', 'handler:sync-driver.fetchall']},
    {id: 2, kind: 'positive', name: 'module-level sqlite3 connection used in a coroutine', path: 'app/lite.py',
      content: 'import sqlite3\nDB = sqlite3.connect("app.db")\n\nasync def load(uid):\n    return DB.execute("SELECT * FROM t WHERE id = ?", (uid,)).fetchone()\n',
      identities: ['load:sync-driver.execute', 'load:sync-driver.fetchone']},
    {id: 3, kind: 'positive', name: 'sync SQLAlchemy Session in a coroutine', path: 'app/sa.py',
      content: 'from sqlalchemy.orm import Session\n\nasync def f(engine):\n    session = Session(engine)\n    rows = session.execute("select 1")\n    session.commit()\n',
      identities: ['f:sync-driver.execute', 'f:sync-driver.commit']},
    {id: 4, kind: 'positive', name: 'Django ORM terminal calls, list() and a plain for in a coroutine', path: 'shop/views.py',
      content: 'from django.http import JsonResponse\n\nasync def a(request, pk):\n    p = Product.objects.get(pk=pk)\n    items = list(Product.objects.filter(live=True))\n    for x in Product.objects.all():\n        print(x)\n    return JsonResponse({})\n',
      identities: ['a:django.get', 'a:django.list', 'a:django.for']},
    {id: 5, kind: 'negative', name: 'wrapped in sync_to_async / to_thread / run_in_executor is the documented fix', path: 'shop/wrapped.py',
      content: 'import asyncio\nimport sqlite3\nfrom asgiref.sync import sync_to_async\nfrom django.db import models\nDB = sqlite3.connect("x")\n\nasync def a(pk):\n    p = await sync_to_async(lambda: Product.objects.get(pk=pk))()\n    r = await asyncio.to_thread(lambda: DB.execute("select 1").fetchone())\n    loop = asyncio.get_running_loop()\n    q = await loop.run_in_executor(None, lambda: DB.execute("select 2"))\n',
      identities: []},
    {id: 6, kind: 'negative', name: 'async variants and async for are not blocking', path: 'shop/async_ok.py',
      content: 'from django.http import JsonResponse\n\nasync def a(pk):\n    p = await Product.objects.aget(pk=pk)\n    async for x in Product.objects.filter(live=True):\n        print(x)\n    n = await Product.objects.acount()\n',
      identities: []},
    {id: 7, kind: 'negative', name: 'the same calls in a plain def are not a coroutine problem', path: 'shop/sync.py',
      content: 'import psycopg2\nfrom django.db import models\n\ndef a(pk):\n    conn = psycopg2.connect("x")\n    return Product.objects.get(pk=pk)\n',
      identities: []},
    {id: 8, kind: 'negative', name: 'a nested sync def inside an async def is not part of the coroutine', path: 'app/nested.py',
      content: 'import sqlite3\n\nasync def a():\n    def worker():\n        return sqlite3.connect("x").execute("select 1")\n    return worker\n',
      identities: []},
    {id: 9, kind: 'negative', name: 'async drivers and AsyncSession are fine', path: 'app/async_ok.py',
      content: 'import asyncpg\nfrom sqlalchemy.ext.asyncio import AsyncSession\n\nasync def a(session: AsyncSession, pool):\n    await session.execute("select 1")\n    await session.commit()\n    conn = await asyncpg.connect("x")\n    return await conn.fetch("select 1")\n',
      identities: []},
    {id: 10, kind: 'missing', name: 'no source for the requested scope is unavailable', path: 'app/none.py', content: null, identities: [], status: 'unavailable'},
    {id: 11, kind: 'malformed', name: 'syntax error file is not evaluated', path: 'app/bad.py', content: 'async def f(:\n', identities: [], status: 'unavailable'},
    {id: 12, kind: 'malformed', name: 'a TypeScript file is outside the Python-only scope and is not evaluated', path: 'src/x.ts', content: 'export const a = 1;\n', identities: [], status: 'unavailable'},
  ],
  'DB-09': [
    {id: 1, kind: 'positive', name: 'Django: one query per object of a queryset, and a nested queryset loop', path: 'shop/views.py', confidence: 'medium',
      content: 'def totals():\n    for order in Order.objects.all():\n        paid = Payment.objects.filter(order_id=order.id).count()\n        print(paid)\n\ndef nested():\n    for post in Post.objects.all():\n        for c in Comment.objects.filter(post=post):\n            print(c)\n',
      identities: ['totals:django.count-in-for', 'nested:django.queryset-in-for']},
    {id: 2, kind: 'positive', name: 'SQLAlchemy session.query(...).first() and session.get per item', path: 'app/repo.py',
      content: 'def f(session, rows):\n    for r in rows:\n        a = session.query(User).filter(User.id == r.uid).first()\n        b = session.get(Team, r.team_id)\n',
      identities: ['f:sqlalchemy.first-in-for', 'f:sqlalchemy.get-in-for']},
    {id: 3, kind: 'positive', name: 'raw SELECT per item with a parameter from the loop', path: 'app/raw.py',
      content: 'def f(cur, ids):\n    for i in ids:\n        cur.execute("SELECT * FROM t WHERE parent = %s", (i,))\n', identities: ['f:raw-sql.execute-in-for']},
    {id: 4, kind: 'positive', name: 'Prisma findMany per user in for-of, medium confidence over a query result', path: 'src/n1.ts', confidence: 'medium',
      content: 'export async function f() {\n  const users = await prisma.user.findMany();\n  for (const u of users) {\n    const posts = await prisma.post.findMany({ where: { authorId: u.id } });\n  }\n}\n',
      identities: ['f:orm.findMany-in-for-of']},
    {id: 5, kind: 'positive', name: 'Sequelize findAll per id in a loop over request ids is low confidence', path: 'src/ids.js', confidence: 'low',
      content: 'async function f(ids) {\n  for (const id of ids) { await Post.findAll({ where: { authorId: id } }); }\n}\n', identities: ['f:orm.findAll-in-for-of']},
    {id: 6, kind: 'positive', name: 'awaited Knex select inside a for loop', path: 'src/knex.js',
      content: 'async function f(rows) {\n  for (const r of rows) { await knex("t").select("a").where({ id: r.id }); }\n}\n', identities: ['f:builder.select-in-for-of']},
    {id: 7, kind: 'negative', name: 'a read that does not depend on the loop variable is DB-04, not N+1', path: 'app/inv.py',
      content: 'def f(items):\n    for i in items:\n        n = Config.objects.filter(key="x").count()\n', identities: []},
    {id: 8, kind: 'negative', name: 'one query with select_related / in-memory lookups has no per-item query', path: 'app/ok.py',
      content: 'def f(ids):\n    rows = Order.objects.filter(id__in=ids).select_related("customer")\n    for o in rows:\n        print(o.customer.name)\n', identities: []},
    {id: 9, kind: 'exception', name: 'Prisma findUnique inside a map callback is batched by the client', path: 'src/batched.ts',
      content: 'export const f = (ids: number[]) => Promise.all(ids.map((id) => prisma.user.findUnique({ where: { id } })));\n', identities: []},
    {id: 10, kind: 'exception', name: 'loop over a short literal list is exempt', path: 'app/few.py',
      content: 'def f():\n    for k in ["a", "b", "c"]:\n        Setting.objects.get(key=k)\n', identities: []},
    {id: 11, kind: 'negative', name: 'a dict/cache get in a loop is not a database read', path: 'app/cache.py',
      content: 'def f(items, cache):\n    for i in items:\n        v = cache.get(i)\n        w = settings_map.get(i)\n', identities: []},
    {id: 14, kind: 'negative', name: 'a plain dict that happens to be named objects is not a Django manager (saleor resolvers.py)', path: 'app/federation.py',
      content: 'def f(ids, queryset):\n    objects = {str(o.id): o for o in queryset.filter(id__in=ids)}\n    return [objects.get(i) for i in ids]\n', identities: []},
    {id: 12, kind: 'missing', name: 'no source for the requested scope is unavailable', path: 'app/none.py', content: null, identities: [], status: 'unavailable'},
    {id: 13, kind: 'malformed', name: 'syntax error file is not evaluated', path: 'app/bad.py', content: 'for x in :\n', identities: [], status: 'unavailable'},
  ],
};
// Per-check context (every evaluation-affecting threshold is explicit; there are no silent defaults).
const contexts = {
  'DB-09': {max_literal_iterations: 5},
  'DB-41': {sync_driver_modules: ['psycopg2', 'pymysql', 'MySQLdb', 'sqlite3', 'mysql.connector', 'pyodbc', 'pg8000', 'psycopg']},
  'DB-14': {select_star_allowed_tables: []},
  'DB-39': {min_literal_offset: 100},
  'DB-13': {max_literal_iterations: 5},
  'DB-23': {unique_key_fields: ['id', 'pk']},
};
/** Contract-v1 input for one case. */
function buildInput(check, c, ctx = {}) {
  const scope = 'file:' + c.path;
  return {schema_version: '1.0', kind: 'input', repository_id: 'github:test/orm', scan_id: 'scan-1', commit_sha: 'a'.repeat(40), check_id: check, detector_version: '1.0.0',
    context: {rule_version: 'orm-1', mode: 'candidate', ...contexts[check], ...c.ctx, ...ctx}, scope: [scope],
    sources: c.content === null ? [] : [{source_id: 'src-1', scope_id: scope, kind: 'static', locator: c.path, content: c.content}]};
}
module.exports = {cases, contexts, buildInput};
